mkdocs.yml
Added celles to conf.yml
Required to be on pages for markdown to html compilation
=> Added celles to subsection CTS

docs/comer/contratos.md
=> Parsed contratos from rst to markdown

mkdocs.yml
References #24 
Added missing pages on yml pages menu
Added blank files for missing pages
=> Create pages admin pub

docs/comer/adm-pub/informes.md
Some endlines and newlines to correct bad display
=> Fixed some endlines reason for no correct display

docs/comer/facturacion.md
Explicació sobre el comportament de les rectificacodres de proveïdor de les FS
=> Start import F1 behaivor

README.md
Added master build url to readme
=> updated readme with master build url

docs/distri/telegestion.md
Add documentation about smart meters events.
=> Add smart meters events reports

landing_page/index.html
Button links of landing page now are relative links to **es/** & **ca/**
=> Updated landing page button links

README.md
Add missing mkdocs command and apt install instructions to get msgmerge and poedit utils.
=> Fix and improve translation instructions of README

requirements.txt
=> Updated requirements to use new markdown-i18n version

mkdocs.yml, mkdocs_es.yml
- Repo url
- Edit in Github
- Google Analytics
=> Add repo info

README.md, merge.sh
Adds a script to merge the actual branch with master
- Uses "msgcat --use-first local.po remote.po -o /locales/es_ES/LC_MESSAGES/messages.po"
- Does git merge origin/master
- **DOES NOT COMMIT OR PUSH**
----
- Added merge.sh
- Updated README.md
=> Add merge script

check_strings.py
Check_strings was not calculating correctly the total strings
=> Update check_strings test with ok length str

docs/extra/css/images.css
This PR is to show all text justified
=> Justify all text

docs/distri/adm-pub/cnmc.md, locales/es_ES/LC_MESSAGES/messages.po
- Added missing ".md" to cnmc resoluciones links
=> Fix cnmc links to resolucions

docs/distri/adm-pub/resoluciones/circular_1-2005.md, locales/es_ES/LC_MESSAGES/messages.po
=> IMP 7NA docs

docs/facturacion/tipos_facturas.md
Fixed invoice types notes that did not include the note.
=> Fixed invoice types notes

PULL_REQUEST_TEMPLATE.md
Closes #249 
This PR is needed, so descriptios are not like this one:
> _\<Empty Description...\>_
=> Add Pull Request Template File

docs/extra/css/images.css
The text in the documentation now appears justified.
- [Telegestió - PowERP Docs](http://builds.gisce.net/powerp-docs/powerp_justify_text/ca/distri/telegestion/#camps-de-connectivitat)
- [Telegestión - PowERP Docs](http://builds.gisce.net/powerp-docs/powerp_justify_text/es/distri/telegestion/#campos-de-conectividad)
=> Justify text

docs/gis/webgis.md
Modificate the headers of the documentation have only one `#`
[Visor](http://builds.gisce.net/powerp-docs/powerp_imp_headers/es/gis/webgis/)
* [NOM DEL FITXER EN CATALÀ #TÍTOL-A-REVISAR](http://builds.gisce.net/powerp-docs/powerp_<branch_name>/ca/<path/to/files>#<title-to-review>)
* [NOM DEL FITXER EN CASTELLÀ #TÍTOL-A-REVISAR](http://builds.gisce.net/powerp-docs/powerp_<branch_name>/es/<path/to/files>#<title-to-review>)
=> Fix headers

docs/gis/webgis.md
Add a note to indicate the format of the files to upload
- CA [Base/Gis/GisWeb/VisorWeb](http://builds.gisce.net/powerp-docs/powerp_imp_doc_update_gis/ca/gis/webgis/#procediment)
- ES [Base/Gis/GisWeb/VisorWeb](http://builds.gisce.net/powerp-docs/powerp_imp_doc_update_gis/es/gis/webgis/#procedimiento)
=> Improve gis load documentation

docs/distri/adm-pub/resoluciones/4666.md
> Fix index of 4666 resolution
* [NOM DEL FITXER EN CATALÀ #TÍTOL-A-REVISAR](http://builds.gisce.net/powerp-docs/powerp_fix_4666_index/ca/distri/adm-pub/resoluciones/4666/)
* [NOM DEL FITXER EN CASTELLÀ #TÍTOL-A-REVISAR](http://builds.gisce.net/powerp-docs/powerp_fix_4666_index/es/distri/adm-pub/resoluciones/4666/)
=> Arreglar indices 4666

docs/distri/adm-pub/resoluciones/4666.md
Update the generation of 4666
- Update generation of 4666
* [Carrega 4666 CA](http://builds.gisce.net/powerp-docs/powerp_imp_4666_load/ca/distri/adm-pub/cnmc/)
* [Carrega 4666 ES](http://builds.gisce.net/powerp-docs/powerp_imp_4666_load/es/distri/adm-pub/cnmc/)
=> Mejorar 4666

docs/distri/adm-pub/resoluciones/4666.md
Add note about the trams de baixa
* [NOM DEL FITXER EN CATALÀ #TÍTOL-A-REVISAR](http://builds.gisce.net/powerp-docs/powerp_<branch_name>/ca/<path/to/files>#<title-to-review>)
* [NOM DEL FITXER EN CASTELLÀ #TÍTOL-A-REVISAR](http://builds.gisce.net/powerp-docs/powerp_<branch_name>/es/<path/to/files>#<title-to-review>)
=> Update 4666 LAT generation

docs/distri/adm-pub/resoluciones/circular_4-2015.md
> Update the selection criteria of F1 and F1 bis
* [4/2015](http://builds.gisce.net/powerp-docs/powerp_updt_42015_f1/ca/distri/adm-pub/resoluciones/circular_4-2015/)
* [4/2015](http://builds.gisce.net/powerp-docs/powerp_updt_42015_f1/es/distri/adm-pub/resoluciones/circular_4-2015/)
=> Update the criteria of selection of F1-F1bis of 4/2015

docs/distri/adm-pub/resoluciones/circular_4-2015.md
Indicate that RE tarifas are not included on F1 and F1bis
* [F1 +F1bis 4/2015 ](http://builds.gisce.net/powerp-docs/powerp_updt_f1_42015_re/ca/distri/adm-pub/resoluciones/circular_4-2015/#f1-informacion-relativa-a-la-demanda-excepto-suministros-a-distribuidores)
* [F1 +F1bis 4/2015 ](http://builds.gisce.net/powerp-docs/powerp_updt_f1_42015_re/es/distri/adm-pub/resoluciones/circular_4-2015/#f1-informacion-relativa-a-la-demanda-excepto-suministros-a-distribuidores)
=> [4/2015] Indicate that RE is not included on F1  and F1bis

docs/gis/webgis.md
Update field firmware
* [Distri/Gis/WebGis/Visor Web](http://builds.gisce.net/powerp-docs/powerp_imp_doc_gis_tg/ca/gis/webgis/#capes-de-telegestio)
* [Distri/Gis/WebGis/Visor Web](http://builds.gisce.net/powerp-docs/powerp_imp_doc_gis_tg/es/gis/webgis/#capas-de-telegestion)
=> Actualizar documentación de telegestión para GIS

docs/comer/adm-pub/cnmc.md, docs/distri/adm-pub/resoluciones/circular_2-2016.md, mkdocs.yml, mkdocs_es.yml, requirements.txt
Adds code highlight support to the documentation
Closes #310
=> Added code highlight support

mkdocs.yml, mkdocs_es.yml, requirements.txt
Closes #309 
ADD Checklist support
N/A
=> ADD Checklist extension

mkdocs.yml, mkdocs_es.yml, requirements.txt
Improve Material interface configurations
N/A -- ANY
=> Imp material interface

docs/distri/adm-pub/resoluciones/circular_4-2015.md
> Remove old criteria
* [CE](http://builds.gisce.net/powerp-docs/powerp_update_f12bis_42015/ca/distri/adm-pub/resoluciones/circular_4-2015/#f12-bis-posicions-en-centres-de-transformacio)
* [Es](http://builds.gisce.net/powerp-docs/powerp_update_f12bis_42015/es/distri/adm-pub/resoluciones/circular_4-2015/#f12-bis-posicions-en-centres-de-transformacio)
=> Remove old restriction

docs/distri/adm-pub/resoluciones/circular_4-2015.md
> Actualitzar documentacion de la generacion del F15 de la 4/2015
* [F15 CA](http://builds.gisce.net/powerp-docs/powerp_imp_f15_42015/ca/distri/adm-pub/resoluciones/circular_4-2015/#f15-fiabilitat)
* [F15 ES](http://builds.gisce.net/powerp-docs/powerp_imp_f15_42015/es/distri/adm-pub/resoluciones/circular_4-2015/#f15-fiabilitat)
=> Mejorar documentacion F15 4/2015

docs/base/GestionATR/apendice.md
Adds ENDESA Jafre conversion
* [Apèndix#endesa-0031](http://builds.gisce.net/powerp-docs/powerp_ENDESA-Jafre/ca/base/GestionATR/apendice/#endesa-0031)
* [Apéndice#endesa-0031](http://builds.gisce.net/powerp-docs/powerp_ENDESA-Jafre/ca/base/GestionATR/apendice/#endesa-0031)
=> IMP Add ENDESA Jafre

docs/base/GestionATR/notificaciones.md
Fix swapped texts at ATR notifications.
* [ATR Notificacions # Configuració](http://builds.gisce.net/powerp-docs/powerp_fix_swapped_texts_notifications_atr/ca/base/GestionATR/notificaciones/#configuracio)
* [ATR Notificaciones # Configuración](http://builds.gisce.net/powerp-docs/powerp_fix_swapped_texts_notifications_atr/es/base/GestionATR/notificaciones/#configuracion)
=> Fix swapped texts notifications atr

docs/gis/webgis.md
> Arreglar documetnacion de telegestion en GIS
* [CA](http://builds.gisce.net/powerp-docs/powerp_fix_tg_gis/ca/gis/webgis/#capas-de-telegestion)
* [ES](http://builds.gisce.net/powerp-docs/powerp_fix_tg_gis/es/gis/webgis/#capas-de-telegestion)
=> Arreglar traduciones de capa de telegestion de GIS

docs/gis/webgis.md
> Mejorar textos de GIS
- [x ] Cambiar persona
* [Vistor web(http://builds.gisce.net/powerp-docs/powerp_imp_gis/ca/gis/webgis/)
* [Visorweb](http://builds.gisce.net/powerp-docs/powerp_imp_gis/es/gis/webgis/)
=> Mejorar textos de GIS

requirements.txt, translate.sh
Añade la instalación de requerimientos para assegurar que el usuario que traduce tiene los requerimientos adecuados.
(Due to #338 )
N/A
=> Mejorar script para realizar traducciones

docs/base/GestionATR/notificaciones.md
Añade la documentación para la gestión de notificaciones para los B1-02 Base/GestionAtr/Notificaciones
* [Notificacions #Configuració de notificacións per B1-02](http://builds.gisce.net/powerp-docs/powerp_docu_notify_conf_motivos_baja_del_arbol_que_esta_mu_alto/ca/base/GestionATR/notificaciones/#configuracio-de-notificacions-per-b1-02)
* [Notificaciones #Configuración de notificaciónes para B1-02](http://builds.gisce.net/powerp-docs/powerp_docu_notify_conf_motivos_baja_del_arbol_que_esta_mu_alto/es/base/GestionATR/notificaciones/#configuracion-de-notificaciones-para-b1-02)
=> Add docu cat config notificacio b102

docs/distri/lbt.md, requirements.txt
Fix requirements with tunned package [Markdown GridTables](https://github.com/jaumef/Markdown-GridTables/)
Fix requirements for [markdown-i18n](https://github.com/gisce/markdown-i18n/pull/37)
=> Fix requirement to work with Markdown 3.0

docs/distri/adm-pub/cnmc.md
- Se añade la documentacion del check regulatior
* [CA](http://builds.gisce.net/powerp-docs/powerp_add_check_regulatori/ca/distri/adm-pub/cnmc/#check-regulatori)
* [ES](http://builds.gisce.net/powerp-docs/powerp_add_check_regulatori/es/distri/adm-pub/cnmc/#check-regulatori)
=> Añadir check regualtorio

docs/distri/posiciones.md, mkdocs.yml, mkdocs_es.yml
Añadir documentacion del calculo de TIs de las posiciones
* [Posicions](http://builds.gisce.net/powerp-docs/powerp_imp_doc_pos_ti/ca/distri/posiciones/)
* [Posiciones](http://builds.gisce.net/powerp-docs/powerp_imp_doc_pos_ti/es/distri/posiciones/)
=> Añadir documentacion del calculo de TIs de las posiciones

mkdocs.yml, mkdocs_es.yml
Sort titles from NAV to be more user-friendly
=> Improve titles order 

docs/distri/adm-pub/resoluciones/5784.md
> Update 4666 doc with new 'estat' fields criteria
> Inventari 5784 (4666)
=> Update 4666 doc with new 'estat' fields criteria

docs/gis/websearch.md
> Corregir la unidad del campo Tensión Subestaciones
* [Buscador CA](http://builds.gisce.net/powerp-docs/powerp_fix_canvi_unitat_tensio_subestacions/ca/gis/websearch/#subestacio)
* [Buscador ES](http://builds.gisce.net/powerp-docs/powerp_fix_canvi_unitat_tensio_subestacions/es/gis/websearch/#subestacio)
=> Corregir la unidad del campo Tensión Subestaciones

docs/distri/medidas.md
- Actualización de la sección `Medidas REE`. 
- Desplegado en el servidor de manuales online.
* `medidas.md`
=> Corrección de errores tipográficos de la sección Medidas de Distribuidora (Junio 2023)

docs/comer/objeciones.md, docs/distri/medidas_generacion.md
- Actualización de la sección `Medidas REE` en Distribuidora y en Comercializadora.
- Desplegado en el servidor de manuales online.
* `medidas_generacion.md`
* `objeciones.md`
=> Correcciones menores en los manuales de Medidas de Distribuidora y de Comercializadora (Julio 2023)
